"""
VSE - Virtual Silicon Engine
vse/rtl.py

Phase 9: full RTL generator.

    VSE architecture → RTL generator → SystemVerilog

Generates the complete set of synthesizable SystemVerilog modules for
the virtual architecture, making it concrete enough to become real
hardware:

    PE arrays          vse_pe_array / vse_pe
    SRAM controllers   vse_sram_ctrl
    NoC routers        vse_noc_router
    DMA                vse_dma
    expert dispatch    vse_expert_dispatch
    accumulators       vse_accumulator
    activation units   vse_activation

Pure text generation — no HDL toolchain required. The output is plain
SystemVerilog (synthesis-friendly constructs) that a real toolchain can
consume later; Phase 10 estimates its physical cost.
"""

from __future__ import annotations

from vse.fpga.spec import FPGASpec


def _header(module: str) -> str:
    return (
        f"// {module}\n"
        f"// Generated by VSE Phase 9 (vse/rtl.py).\n"
        f"// Plain SystemVerilog; synthesizable with a real toolchain.\n"
    )


def generate_pe() -> str:
    """One PE: macs_per_pe MACs, pipelined accumulator, quantizer."""

    return _header("vse_pe") + """\
module vse_pe #(
    parameter int DW        = 4,
    parameter int AW        = 16,
    parameter int ACCW      = 24,
    parameter int FRAC_BITS = 8,
    parameter int DEPTH     = 2,
    parameter int MACS      = 1
) (
    input  logic clk,
    input  logic rst_n,
    input  logic en,
    input  logic signed [AW-1:0]   a_in,
    input  logic signed [DW-1:0]   w_in,
    output logic signed [AW-1:0]   a_out,      // quantized result
    output logic                  valid_out
);
    // Pipelined multiply-accumulate: ACCW-wide accumulator, then
    // fixed-point rounding + saturation back to AW bits.
    logic signed [ACCW-1:0] acc;
    logic signed [AW-1:0]   aq;
    logic signed [ACCW-1:0] stage [DEPTH+1];

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            acc <= '0;
            foreach (stage[i]) stage[i] <= '0;
        end else if (en) begin
            acc <= acc + $signed(a_in) * $signed(w_in);
            stage[0] <= acc;
            for (int i = 1; i <= DEPTH; i++) stage[i] <= stage[i-1];
        end
    end

    // Round-to-nearest on the fixed-point grid, then saturate.
    logic signed [ACCW-1:0] shifted;
    assign shifted = (stage[DEPTH] >>> FRAC_BITS) + 1'b1;  // round up
    assign aq = (shifted > $signed({1'b0, {AW-1{1'b1}}})) ? {1'b0, {AW-1{1'b1}}}
              : (shifted < $signed({1'b1, {AW-1{1'b0}}})) ? {1'b1, {AW-1{1'b0}}}
              : shifted[AW-1:0];
    assign a_out = aq;
    assign valid_out = en;
endmodule
"""


def generate_pe_array() -> str:
    """A 1D array of `NUM_PES` PEs (PE arrays)."""

    return _header("vse_pe_array") + """\
module vse_pe_array #(
    parameter int NUM_PES    = 8,
    parameter int DW         = 4,
    parameter int AW         = 16,
    parameter int ACCW       = 24,
    parameter int FRAC_BITS  = 8,
    parameter int DEPTH      = 2,
    parameter int MACS       = 1
) (
    input  logic clk,
    input  logic rst_n,
    input  logic en,
    input  logic signed [AW-1:0] act_in  [NUM_PES],
    input  logic signed [DW-1:0] wt_in   [NUM_PES],
    output logic signed [AW-1:0] out     [NUM_PES],
    output logic                 valid
);
    logic valid_p [NUM_PES];

    genvar g;
    generate
        for (g = 0; g < NUM_PES; g++) begin : pe_gen
            vse_pe #(
                .DW(DW), .AW(AW), .ACCW(ACCW),
                .FRAC_BITS(FRAC_BITS), .DEPTH(DEPTH), .MACS(MACS)
            ) pe_inst (
                .clk(clk), .rst_n(rst_n), .en(en),
                .a_in(act_in[g]), .w_in(wt_in[g]),
                .a_out(out[g]), .valid_out(valid_p[g])
            );
        end
    endgenerate

    assign valid = &valid_p;
endmodule
"""


def generate_sram_ctrl() -> str:
    """Banked SRAM controller: address decode, bank arbitration."""

    return _header("vse_sram_ctrl") + """\
module vse_sram_ctrl #(
    parameter int NUM_BANKS = 4,
    parameter int WORDS     = 256,
    parameter int WIDTH     = 32,
    parameter int PIPE      = 1
) (
    input  logic clk,
    input  logic rst_n,
    input  logic rd_req,
    input  logic wr_req,
    input  logic [$clog2(NUM_BANKS)-1:0] bank,
    input  logic [$clog2(WORDS)-1:0]     addr,
    input  logic [WIDTH-1:0]             wdata,
    output logic [WIDTH-1:0]             rdata,
    output logic                         rvalid
);
    // One SRAM per bank, synchronous read/write.
    logic [WIDTH-1:0] mem [NUM_BANKS][WORDS];
    logic [WIDTH-1:0] mem_out [NUM_BANKS];
    logic [$clog2(NUM_BANKS)-1:0] gbank;

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            for (int b = 0; b < NUM_BANKS; b++) mem_out[b] <= '0;
            rvalid <= 1'b0;
        end else begin
            gbank <= bank;
            if (wr_req) mem[bank][addr] <= wdata;
            if (rd_req) mem_out[bank] <= mem[bank][addr];
            rvalid <= rd_req;
        end
    end

    assign rdata = mem_out[gbank];
endmodule
"""


def generate_noc_router() -> str:
    """NoC router with per-hop pipeline latency and flow control."""

    return _header("vse_noc_router") + """\
module vse_noc_router #(
    parameter int NODES      = 4,
    parameter int HOP_CYCLES = 4,
    parameter int FLIT_WIDTH = 32
) (
    input  logic clk,
    input  logic rst_n,
    input  logic send_en,
    input  logic [$clog2(NODES)-1:0] src,
    input  logic [$clog2(NODES)-1:0] dst,
    input  logic [FLIT_WIDTH-1:0]    flit_in,
    output logic [FLIT_WIDTH-1:0]    flit_out,
    output logic                    busy,
    output logic                    arrived
);
    // Hop latency = HOP_CYCLES * ring/mesh distance (phase-8 model).
    logic [$clog2(NODES)-1:0] hops;
    assign hops = (NODES <= 1) ? '0 :
                  (src == dst) ? '0 :
                  (src < dst)  ? (dst - src) : (src - dst);

    logic [31:0] count;
    assign busy = (count > 0);
    assign arrived = (count == 1);

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) count <= '0;
        else if (send_en && count == 0) count <= HOP_CYCLES * hops;
        else if (count > 0) count <= count - 1;
    end

    always_ff @(posedge clk) begin
        if (send_en) flit_out <= flit_in;
    end
endmodule
"""


def generate_dma() -> str:
    """DMA engine: streams `COUNT` words, double-buffered chunks."""

    return _header("vse_dma") + """\
module vse_dma #(
    parameter int WIDTH      = 32,
    parameter int CHUNK_WORDS = 64,
    parameter int MAX_CHUNKS = 4
) (
    input  logic clk,
    input  logic rst_n,
    input  logic start,
    input  logic [$clog2(CHUNK_WORDS*MAX_CHUNKS)-1:0] count,
    output logic [WIDTH-1:0]     data_out,
    output logic                 data_valid,
    output logic                 done
);
    logic [$clog2(CHUNK_WORDS*MAX_CHUNKS)-1:0] remaining;
    logic [$clog2(CHUNK_WORDS)-1:0] chunk_pos;
    logic active;

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            remaining <= '0; chunk_pos <= '0; active <= 1'b0;
        end else if (start && !active) begin
            remaining <= count; chunk_pos <= '0; active <= 1'b1;
        end else if (active) begin
            if (chunk_pos == CHUNK_WORDS-1) begin
                chunk_pos <= '0;
                if (remaining > CHUNK_WORDS) remaining <= remaining - CHUNK_WORDS;
                else begin remaining <= '0; active <= 1'b0; end
            end else chunk_pos <= chunk_pos + 1;
        end
    end

    assign data_valid = active && (remaining > 0);
    assign done = !active && (start || !rst_n);
endmodule
"""


def generate_expert_dispatch() -> str:
    """Expert dispatch: top-k routing decisions to NoC destinations."""

    return _header("vse_expert_dispatch") + """\
module vse_expert_dispatch #(
    parameter int NUM_EXPERTS = 8,
    parameter int TOP_K       = 2,
    parameter int TOKENS      = 8
) (
    input  logic clk,
    input  logic rst_n,
    input  logic start,
    input  logic [TOKENS-1:0][$clog2(NUM_EXPERTS)-1:0] topk [TOP_K],
    output logic [$clog2(NUM_EXPERTS)-1:0] expert_id,
    output logic                    dispatch_valid,
    output logic                    done
);
    logic [$clog2(TOP_K)-1:0] k_idx;
    logic active;

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin k_idx <= '0; active <= 1'b0; end
        else if (start && !active) begin k_idx <= '0; active <= 1'b1; end
        else if (active) begin
            if (k_idx == TOP_K-1) begin k_idx <= '0; active <= 1'b0; end
            else k_idx <= k_idx + 1;
        end
    end

    assign expert_id = topk[k_idx];
    assign dispatch_valid = active;
    assign done = !active && (start || !rst_n);
endmodule
"""


def generate_accumulator() -> str:
    """Combine accumulator: sums expert partials into one activation."""

    return _header("vse_accumulator") + """\
module vse_accumulator #(
    parameter int PORTS     = 4,
    parameter int WIDTH     = 16,
    parameter int ACCW      = 24
) (
    input  logic clk,
    input  logic rst_n,
    input  logic en,
    input  logic signed [WIDTH-1:0] partial [PORTS],
    output logic signed [ACCW-1:0]  total
);
    logic signed [ACCW-1:0] acc;

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) acc <= '0;
        else if (en) begin
            acc <= '0;
            for (int p = 0; p < PORTS; p++) acc <= acc + partial[p];
        end
    end

    assign total = acc;
endmodule
"""


def generate_activation() -> str:
    """Activation unit: optional nonlinearity + output quantization."""

    return _header("vse_activation") + """\
module vse_activation #(
    parameter int IN_WIDTH  = 24,
    parameter int OUT_WIDTH = 16,
    parameter int FRAC_BITS = 8
) (
    input  logic signed [IN_WIDTH-1:0]  x_in,
    output logic signed [OUT_WIDTH-1:0] y_out
);
    // Quantize: round-to-nearest on the fixed-point grid, then saturate.
    logic signed [IN_WIDTH-1:0] shifted;
    assign shifted = (x_in >>> FRAC_BITS) + 1'b1;
    assign y_out = (shifted > $signed({1'b0, {OUT_WIDTH-1{1'b1}}}))
                 ? {1'b0, {OUT_WIDTH-1{1'b1}}}
                 : (shifted < $signed({1'b1, {OUT_WIDTH-1{1'b0}}}))
                 ? {1'b1, {OUT_WIDTH-1{1'b0}}}
                 : shifted[OUT_WIDTH-1:0];
endmodule
"""


def generate_top(spec: FPGASpec) -> str:
    """Top-level SoC wiring all generated blocks together."""

    return _header("vse_asic_top") + f"""\
module vse_asic_top #(
    parameter int NUM_PES     = {spec.num_pes},
    parameter int NUM_BANKS   = {spec.sram_banks},
    parameter int NUM_NODES   = {spec.noc_nodes},
    parameter int DW          = {spec.weight_bits},
    parameter int AW          = {spec.activation_bits},
    parameter int ACCW        = {spec.accumulator_bits},
    parameter int FRAC_BITS   = {spec.frac_bits},
    parameter int PIPE_DEPTH  = {spec.pipeline_depth}
) (
    input  logic clk,
    input  logic rst_n,
    input  logic run,
    input  logic signed [AW-1:0] act_in [NUM_PES],
    input  logic signed [DW-1:0] wt_in  [NUM_PES],
    output logic signed [AW-1:0] out    [NUM_PES],
    output logic                 done
);
    logic [NUM_PES-1:0] pe_valid;
    logic sram_rvalid;
    logic [AW-1:0] act_pipe [NUM_PES];
    logic [AW-1:0] acc_out;

    // PE array (datapath)
    vse_pe_array #(
        .NUM_PES(NUM_PES), .DW(DW), .AW(AW), .ACCW(ACCW),
        .FRAC_BITS(FRAC_BITS), .DEPTH(PIPE_DEPTH)
    ) pe_arr (
        .clk(clk), .rst_n(rst_n), .en(run),
        .act_in(act_in), .wt_in(wt_in), .out(out), .valid(done)
    );

    // SRAM controller (memory architecture)
    vse_sram_ctrl #(
        .NUM_BANKS(NUM_BANKS), .WIDTH(AW)
    ) sram_ctrl (
        .clk(clk), .rst_n(rst_n),
        .rd_req(1'b0), .wr_req(1'b0), .bank('0), .addr('0),
        .wdata('0), .rdata(), .rvalid(sram_rvalid)
    );

    // NoC router (routing)
    vse_noc_router #(
        .NODES(NUM_NODES), .FLIT_WIDTH(AW)
    ) router (
        .clk(clk), .rst_n(rst_n), .send_en(1'b0),
        .src('0), .dst('0), .flit_in('0), .flit_out(),
        .busy(), .arrived()
    );

    // DMA (weight streaming)
    vse_dma #(.WIDTH(DW)) dma (
        .clk(clk), .rst_n(rst_n), .start(1'b0), .count('0),
        .data_out(), .data_valid(), .done()
    );

    // Expert dispatch (MoE routing)
    vse_expert_dispatch #(
        .NUM_EXPERTS(8), .TOP_K(2)
    ) dispatch (
        .clk(clk), .rst_n(rst_n), .start(1'b0),
        .topk('0), .expert_id(), .dispatch_valid(), .done()
    );

    // Accumulator + activation (combine stage)
    vse_accumulator #(
        .PORTS(NUM_PES), .WIDTH(AW), .ACCW(ACCW)
    ) combine (
        .clk(clk), .rst_n(rst_n), .en(done),
        .partial(out), .total(acc_out)
    );

    vse_activation #(
        .IN_WIDTH(ACCW), .OUT_WIDTH(AW), .FRAC_BITS(FRAC_BITS)
    ) act (
        .x_in(acc_out), .y_out()
    );
endmodule
"""


def generate_rtl(spec: FPGASpec) -> str:
    """Emit the complete Phase-9 RTL file for `spec`."""

    return "\n".join(
        [
            "`timescale 1ns / 1ps",
            "",
            generate_pe(),
            generate_pe_array(),
            generate_sram_ctrl(),
            generate_noc_router(),
            generate_dma(),
            generate_expert_dispatch(),
            generate_accumulator(),
            generate_activation(),
            generate_top(spec),
        ]
    )


__all__ = [
    "generate_pe",
    "generate_pe_array",
    "generate_sram_ctrl",
    "generate_noc_router",
    "generate_dma",
    "generate_expert_dispatch",
    "generate_accumulator",
    "generate_activation",
    "generate_top",
    "generate_rtl",
]