SIM_NAME = "stock_analyser"
TOPIC = "sim_stock"
TIMEFRAMES = ("1D", "15m", "5m", "1m")  # V1 uses 1D + 15m
DEFAULT_TF = "1D"
FEE_BPS = 5.0
SLIPPAGE_BPS = 5.0
ATR_N = 14
SEED_SYMBOLS = [
    "RELIANCE", "TCS", "INFY", "HDFCBANK", "ICICIBANK",
    "SBIN", "ITC", "BHARTIARTL", "LT", "HINDUNILVR",
    "KOTAKBANK", "AXISBANK", "BAJFINANCE", "ASIANPAINT", "MARUTI",
]
UNIVERSES = ("NIFTY_200", "OPTIONS_ELIGIBLE", "ALL_EQUITIES", "MY_RESEARCH_UNIVERSE")
FINDING_STATUS = (
    "HYPOTHESIS", "SUPPORTED", "ROBUST", "REFUTED",
    "REGIME_DEPENDENT", "INSUFFICIENT_DATA", "SUPERSEDED",
)
