birth_rate: 0.04
death_rate: 0.01
fertile_max_age: 50
fertile_min_age: 15
grid_height: 50
grid_width: 50
healer_healing_cost: 0.5
healer_healing_rate: 0.1
initial_healers: 10
initial_pop: 30
initial_toolmakers: 10
initial_traders: 10
max_age: 60
metabolism: 1
seed: None
toolmaker_cost: 1.0
toolmaker_production_rate: 0.1
toolmaker_quality: 0.1
trader_margin: 0.05
trader_range: 2
vision: 2
years: 20
