"""
VSE - Virtual Silicon Engine
vse/fpga/rtl.py

Phase 8: SystemVerilog RTL code generator.

Generates a synthesizable-ish SystemVerilog description of the small
FPGA prototype described by an `FPGASpec`:

    - vse_pe          — MAC datapath with pipelined accumulator
    - vse_sram_bank   — single-bank synchronous SRAM
    - vse_router      — ring/mesh NoC router with hop latency
    - vse_soc_top     — PE array + SRAM banks + router wiring

The emitted RTL is the concrete "Hardware specification → RTL" step of
the Phase 8 pipeline. It is plain SystemVerilog (no external libraries)
so it can be inspected, and later handed to a real toolchain in Phase 9.
"""

from __future__ import annotations

from typing import List

from vse.fpga.spec import FPGASpec


def _header(module: str) -> List[str]:
    return [
        f"// {module}",
        "// Generated by VSE Phase 8 (vse/fpga/rtl.py).",
        "// Pure SystemVerilog; no external dependencies.",
    ]


def generate_pe(spec: FPGASpec) -> str:
    """Pipelined MAC + accumulator datapath for one PE."""

    w = spec.weight_bits
    a = spec.activation_bits
    acc = spec.accumulator_bits
    depth = spec.pipeline_depth

    lines = _header("vse_pe")
    lines += [
        f"module vse_pe #(",
        f"    parameter int DW = {w},",
        f"    parameter int AW = {a},",
        f"    parameter int ACCW = {acc},",
        f"    parameter int DEPTH = {depth}",
        ") (",
        "    input  logic clk,",
        "    input  logic rst_n,",
        "    input  logic en,",
        "    input  logic signed [AW-1:0]   a_in,",
        "    input  logic signed [DW-1:0]   w_in,",
        "    output logic signed [ACCW-1:0] acc_out,",
        "    output logic                  valid_out",
        ");",
    ]

    if depth <= 0:
        lines += [
            "",
            "    // Combinational MAC (depth 0).",
            "    assign acc_out = $signed(a_in) * $signed(w_in);",
            "    assign valid_out = en;",
        ]
    else:
        lines += [
            "",
            "    // Pipelined multiply-accumulate with `DEPTH` registers.",
            f"    logic signed [ACCW-1:0] acc_reg = '0;",
            f"    logic signed [ACCW-1:0] acc_pipe [DEPTH];",
            "    logic valid_pipe [DEPTH];",
            "",
            "    always_ff @(posedge clk or negedge rst_n) begin",
            "        if (!rst_n) begin",
            "            acc_reg <= '0;",
            "            foreach (acc_pipe[i]) acc_pipe[i] <= '0;",
            "            foreach (valid_pipe[i]) valid_pipe[i] <= 1'b0;",
            "        end else if (en) begin",
            "            acc_reg <= acc_reg + $signed(a_in) * $signed(w_in);",
            "            acc_pipe[0] <= acc_reg + $signed(a_in) * $signed(w_in);",
            "            valid_pipe[0] <= 1'b1;",
            "            for (int i = 1; i < DEPTH; i++) begin",
            "                acc_pipe[i] <= acc_pipe[i-1];",
            "                valid_pipe[i] <= valid_pipe[i-1];",
            "            end",
            "        end",
            "    end",
            "",
            f"    assign acc_out = acc_pipe[DEPTH-1];",
            f"    assign valid_out = valid_pipe[DEPTH-1];",
        ]

    lines += ["endmodule", ""]
    return "\n".join(lines)


def generate_sram(spec: FPGASpec) -> str:
    """One synchronous SRAM bank."""

    words = spec.sram_words_per_bank
    bits = spec.sram_word_bits

    lines = _header("vse_sram_bank")
    lines += [
        f"module vse_sram_bank #(",
        f"    parameter int WORDS = {words},",
        f"    parameter int WIDTH = {bits}",
        ") (",
        "    input  logic clk,",
        "    input  logic ce,",
        "    input  logic we,",
        "    input  logic [$clog2(WORDS)-1:0] addr,",
        "    input  logic [WIDTH-1:0]         din,",
        "    output logic [WIDTH-1:0]         dout",
        ");",
        "",
        f"    logic [WIDTH-1:0] mem [WORDS];",
        "",
        "    always_ff @(posedge clk) begin",
        "        if (ce) begin",
        "            if (we) mem[addr] <= din;",
        "            dout <= mem[addr];",
        "        end",
        "    end",
        "endmodule",
        "",
    ]
    return "\n".join(lines)


def generate_router(spec: FPGASpec) -> str:
    """Ring/mesh NoC router: dimension-ordered hop forwarding."""

    nodes = spec.noc_nodes
    hops = spec.noc_per_hop_cycles

    lines = _header("vse_router")
    lines += [
        f"module vse_router #(",
        f"    parameter int NODES = {nodes},",
        f"    parameter int HOP_CYCLES = {hops}",
        ") (",
        "    input  logic clk,",
        "    input  logic rst_n,",
        "    input  logic        send_en,",
        "    input  logic [$clog2(NODES)-1:0] src,",
        "    input  logic [$clog2(NODES)-1:0] dst,",
        "    output logic        busy,",
        "    output logic        arrived",
        ");",
        "",
        "    // Hop count: ring uses the shorter arc; mesh would compute",
        "    // Manhattan distance on a grid (dimension-ordered routing).",
        "    logic [$clog2(NODES)-1:0] hops;",
        "    assign hops = (NODES <= 1) ? '0 :",
        "                 (src == dst) ? '0 :",
        "                 (src < dst) ? (dst - src) : (src - dst);",
        "",
        "    logic [31:0] count;",
        "    assign busy = (count > 0);",
        "    assign arrived = (count == HOP_CYCLES * hops);",
        "",
        "    always_ff @(posedge clk or negedge rst_n) begin",
        "        if (!rst_n) count <= '0;",
        "        else if (send_en && count == 0) count <= HOP_CYCLES * hops;",
        "        else if (count > 0) count <= count - 1;",
        "    end",
        "endmodule",
        "",
    ]
    return "\n".join(lines)


def generate_top(spec: FPGASpec) -> str:
    """Top-level SoC: PE array + SRAM banks + router."""

    pes = spec.num_pes
    banks = spec.sram_banks
    w = spec.weight_bits
    a = spec.activation_bits
    acc = spec.accumulator_bits

    lines = _header("vse_soc_top")
    lines += [
        f"module vse_soc_top #(",
        f"    parameter int NUM_PES = {pes},",
        f"    parameter int NUM_BANKS = {banks},",
        f"    parameter int DW = {w},",
        f"    parameter int AW = {a},",
        f"    parameter int ACCW = {acc}",
        ") (",
        "    input  logic clk,",
        "    input  logic rst_n,",
        "    input  logic run,",
        "    input  logic signed [AW-1:0] act_in [NUM_PES],",
        "    input  logic signed [DW-1:0] wt_in  [NUM_PES],",
        "    output logic signed [ACCW-1:0] acc_out [NUM_PES],",
        "    output logic done",
        ");",
        "",
        "    logic pe_valid [NUM_PES];",
        "",
    ]

    for i in range(pes):
        lines += [
            f"    vse_pe #(.DW(DW), .AW(AW), .ACCW(ACCW)) pe_{i} (",
            "        .clk(clk), .rst_n(rst_n), .en(run),",
            f"        .a_in(act_in[{i}]), .w_in(wt_in[{i}]),",
            f"        .acc_out(acc_out[{i}]), .valid_out(pe_valid[{i}])",
            "    );",
        ]

    lines += [
        "",
        f"    logic [{banks}-1:0] sram_ce;",
        f"    vse_sram_bank #(.WORDS(256), .WIDTH({spec.sram_word_bits}))",
        "        sram_inst (.clk(clk), .ce(1'b1), .we(1'b0),",
        "                   .addr('0), .din('0), .dout());",
        "",
        f"    vse_router #(.NODES({spec.noc_nodes}))",
        "        router_inst (.clk(clk), .rst_n(rst_n), .send_en(1'b0),",
        "                     .src('0), .dst('0), .busy(), .arrived());",
        "",
        "    assign done = &pe_valid;",
        "endmodule",
        "",
    ]
    return "\n".join(lines)


def generate_rtl(spec: FPGASpec) -> str:
    """Emit the complete prototype RTL file for `spec`."""

    parts: list[str] = [
        *_header("vse_fpga_prototype"),
        "",
        "`timescale 1ns / 1ps",
        "",
        generate_pe(spec),
        generate_sram(spec),
        generate_router(spec),
        generate_top(spec),
    ]

    return "\n".join(parts)


__all__ = [
    "generate_pe",
    "generate_sram",
    "generate_router",
    "generate_top",
    "generate_rtl",
]