#!/usr/bin/env python3
"""C6/C8: render status.md from hypotheses + dev_change events.

Regenerates Current Capability (from capability_claim hypotheses + a
generated-cache marker), Known Gaps (from known_gap hypotheses) and Recent
Changes (hybrid of dev_change events + uncovered manual bullets). All other
content is preserved verbatim.
"""

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))
sys.path.insert(0, str(PROJECT_ROOT / "codebase"))

from kernel.hypothesis.hypothesis_engine import hypothesis_engine
from scripts.lib.citations import discover_status_files, extract_module_name
from scripts.seed_hypotheses import seed_all
from scripts.render_recent_changes import load_dev_change_events, render_recent_changes

GENERATED_NOTE = "> Capability section generated by `scripts/render_status.py` — hand-edits are overwritten."
CAP_TITLE = "Current Capability"
GAP_TITLE = "Known Gaps"
RECENT_TITLE = "Recent Changes"


def cap_bullet(h):
    raw = h.metadata.get("evidence_raw")
    if raw:
        return f"- {h.title} \u2014 {raw}"
    ev = h.metadata.get("evidence_path", "")
    sym = h.metadata.get("evidence_symbol", "")
    if ev and sym:
        return f"- {h.title} \u2014 `{ev}:{sym}()`"
    return f"- {h.title}"


def gap_bullet(h):
    sev = h.metadata.get("severity", "")
    return f"- {h.title} \u2014 {sev}" if sev else f"- {h.title}"


def _id_key(h):
    try:
        return int(h.hypothesis_id.rsplit("_", 1)[1])
    except ValueError:
        return 0


def render_status_file(path, engine, write=False):
    text = path.read_text(encoding="utf-8")
    module = extract_module_name(path)
    caps = sorted(
        (h for h in engine.get_by_type("capability_claim")
         if h.hypothesis_id.startswith(f"cap_{module}_")),
        key=_id_key,
    )
    gaps = sorted(
        (h for h in engine.get_by_type("known_gap")
         if h.hypothesis_id.startswith(f"gap_{module}_")),
        key=_id_key,
    )
    events = load_dev_change_events(module=module)
    out = []
    for header, content in _split_blocks(text):
        if header is None:
            out.append((None, content))
            continue
        title = header.strip()[3:]
        if title.startswith(CAP_TITLE):
            bullets = [GENERATED_NOTE] + [cap_bullet(h) for h in caps]
            out.append((header, bullets + [""]))
        elif title.startswith(GAP_TITLE):
            out.append((header, [gap_bullet(h) for h in gaps] + [""]))
        elif title.startswith(RECENT_TITLE):
            out.append((header, render_recent_changes(content, events) + [""]))
        else:
            out.append((header, content))
    new_text = _join_blocks(out)
    if write:
        path.write_text(new_text, encoding="utf-8")
    return new_text


def _split_blocks(text):
    lines = text.splitlines()
    blocks = []
    header, content = None, []
    for line in lines:
        if line.strip().startswith("## "):
            if header is not None or content:
                blocks.append((header, content))
            header, content = line, []
        else:
            content.append(line)
    blocks.append((header, content))
    return blocks


def _join_blocks(blocks):
    lines = []
    for header, content in blocks:
        if header is not None:
            lines.append(header)
        lines.extend(content)
    return "\n".join(lines)


def main():
    quiet = "--quiet" in sys.argv or "-q" in sys.argv
    write = "--write" in sys.argv
    module = None
    args = sys.argv[1:]
    for i, a in enumerate(args):
        if a == "--module" and i + 1 < len(args):
            module = args[i + 1]
    seed_all(hypothesis_engine)
    files = [p for p in discover_status_files()
             if not module or extract_module_name(p) == module]
    for path in files:
        new_text = render_status_file(path, hypothesis_engine, write=write)
        verb = "updated" if write else "preview"
        print(f"{verb} {path.relative_to(PROJECT_ROOT)}")
        if not quiet:
            for line in new_text.splitlines():
                if line.strip().startswith("- ") or line.strip().startswith("> Capability"):
                    print(f"  {line[:80]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())