#!/usr/bin/env python3
"""O3: render project-root INDEX.md health badge from inventory + validate.

Aggregates report_inventory, report_schema_check and validate_capabilities
into a deterministic INDEX.md (idempotent given unchanged inputs).
"""

import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))
sys.path.insert(0, str(PROJECT_ROOT / "codebase"))

from agent_core.tools.code_rag.tools import (
    report_inventory_tool,
    report_schema_check_tool,
)
from kernel.hypothesis.hypothesis_engine import hypothesis_engine

GENERATED_NOTE = "> Generated by `scripts/render_index.py` — hand-edits are overwritten."
INDEX_PATH = PROJECT_ROOT / "INDEX.md"


def collect() -> dict:
    inv = json.loads(report_inventory_tool({}))["reports"]
    schema = json.loads(report_schema_check_tool({}))["reports"]
    from scripts.seed_hypotheses import seed_all
    from scripts.validate_capabilities import validate_capabilities
    seed_all(hypothesis_engine)
    val = validate_capabilities(hypothesis_engine)
    schema_issues = sum(len(r["issues"]) for r in schema)
    empty = [e["path"] for e in inv if e["empty"]]
    roles = {}
    for e in inv:
        roles[e["role"]] = roles.get(e["role"], 0) + 1
    return {
        "reports": len(inv), "roles": roles, "empty": empty,
        "schema_clean": schema_issues == 0, "schema_issues": schema_issues,
        "passed": val["passed"], "failed": val["failed"], "skipped": val["skipped"],
        "regressions": len(val["regressions"]),
        "modules": val["modules"],
    }


def render(data: dict) -> str:
    badge = (
        f"VALIDATE {data['passed']}/{data['passed'] + data['failed'] + data['skipped']}"
        f" PASS | FAIL {data['failed']} | SKIP {data['skipped']}"
        f" | REGRESSIONS {data['regressions']}"
        f" | SCHEMA {'CLEAN' if data['schema_clean'] else str(data['schema_issues']) + ' ISSUES'}"
    )
    lines = [
        "# Project Health Index",
        GENERATED_NOTE,
        "",
        f"Badge: `{badge}`",
        "",
        "## Reports",
        f"- Total: {data['reports']} (status {data['roles'].get('status', 0)}, "
        f"roadmap {data['roles'].get('roadmap', 0)}, readme {data['roles'].get('readme', 0)}, "
        f"other {data['roles'].get('other', 0)})",
        f"- Schema check: {'clean' if data['schema_clean'] else f'{data["schema_issues"]} issue(s)'}",
        f"- Empty reports: {len(data['empty'])}",
    ]
    if data["empty"]:
        lines += [f"  - {e}" for e in data["empty"]]
    lines += [
        "",
        "## Capability validation",
        f"- Passed: {data['passed']}",
        f"- Failed: {data['failed']}",
        f"- Skipped: {data['skipped']}",
        f"- Regressions: {data['regressions']}",
    ]
    for mod in sorted(data["modules"]):
        c = data["modules"][mod]
        lines.append(f"- {mod}: {c['passed']} passed, {c['failed']} failed, {c['skipped']} skipped")
    return "\n".join(lines) + "\n"


def main():
    write = "--write" in sys.argv
    quiet = "--quiet" in sys.argv or "-q" in sys.argv
    if "--json" in sys.argv:
        print(json.dumps(collect(), separators=(",", ":")))
        return 0
    text = render(collect())
    if write:
        INDEX_PATH.write_text(text, encoding="utf-8")
        print(f"wrote {INDEX_PATH.relative_to(PROJECT_ROOT)}")
    elif not quiet:
        print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())